//monsters array list
var monsters_arr = [{
    src: 'assets/monster1_Spritesheet4x3.png',
    width: 60,
    height: 70,
    regX: 30,
    regY: 56,
    hitOffset: -30,
    life: 20,
    resource: 2,
    ammo: {},
    bar: { width: 30, height: 5, offset: -60 }
},
{
    src: 'assets/monster2_Spritesheet4x3.png',
    width: 60,
    height: 70,
    regX: 30,
    regY: 56,
    hitOffset: -30,
    resource: 4,
    life: 40,
    ammo: { src: 'assets/item_monsterammo2.png', regX: 7, regY: 0, speed: 4, life: 1.5, time: 1, freeze: 0, rotate: false, shotOffset: -30, range: 200 },
    bar: { width: 40, height: 5, offset: -60 }
},
{
    src: 'assets/monster3_Spritesheet4x3.png',
    width: 60,
    height: 70,
    regX: 30,
    regY: 56,
    hitOffset: -30,
    resource: 6,
    life: 80,
    ammo: { src: 'assets/item_monsterammo3.png', regX: 7, regY: 0, speed: 4, life: 2.5, time: 1, freeze: 0, rotate: false, shotOffset: -30, range: 200 },
    bar: { width: 30, height: 5, offset: -60 }
},
{
    src: 'assets/monster4_Spritesheet4x3.png',
    width: 60,
    height: 70,
    regX: 30,
    regY: 56,
    hitOffset: -30,
    resource: 8,
    life: 120,
    ammo: { src: 'assets/item_monsterammo4.png', regX: 7, regY: 0, speed: 4, life: 4, time: 1, freeze: 0, rotate: false, shotOffset: -30, range: 200 },
    bar: { width: 30, height: 5, offset: -60 }
},
{
    src: 'assets/monster5_Spritesheet4x3.png',
    width: 60,
    height: 70,
    regX: 30,
    regY: 56,
    hitOffset: -30,
    resource: 10,
    life: 200,
    ammo: { src: 'assets/item_monsterammo5.png', regX: 7, regY: 0, speed: 4, life: 6, time: 1, freeze: 0, rotate: false, shotOffset: -30, range: 200 },
    bar: { width: 30, height: 5, offset: -60 }
},
{
    src: 'assets/monster6_Spritesheet4x3.png',
    width: 60,
    height: 70,
    regX: 30,
    regY: 56,
    hitOffset: -30,
    resource: 15,
    life: 600,
    ammo: { src: 'assets/item_monsterammo6.png', regX: 7, regY: 0, speed: 4, life: 12, time: 1, freeze: 0, rotate: false, shotOffset: -30, range: 200 },
    bar: { width: 30, height: 5, offset: -60 }
}];

//towers array list				
var towers_arr = [{
    name: 'base',
    image: { src: 'assets/item_tower0.png', regX: 32, regY: 40 },
    icon: { src: 'assets/icon_tower0.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
    ammo: {},
    resource: 5,
    hitOffset: -30,
    life: 0,
    bar: { width: 40, height: 5, offset: -60 },
},
{
    name: 'omnom',
    sound: 'assets/sounds/ammo_axe.ogg',
    image: { src: 'assets/item_tower2.png', regX: 32, regY: 90 },
    icon: { src: 'assets/icon_tower2.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
    ammo: { src: 'assets/item_ammo2.png', regX: 0, regY: 50, speed: 50, get life() { return 0.4 * ammoFire; }, time: 0.1, freeze: 0, rotate: false, shotOffset: 0, range: 150 },
    resource: 30,
    hitOffset: -30,
    life: 60,
    bar: { width: 40, height: 5, offset: -60 },
    upgrade: [{
        name: 'upgrade_1',
        image: { src: 'assets/item_tower2_1.png', regX: 32, regY: 90 },
        icon: { src: 'assets/icon_tower2_1.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
        ammo: { src: 'assets/item_ammo2.png', regX: 0, regY: 50, speed: 50, get life() { return 0.6 * ammoFire; }, time: 0.1, freeze: 0, rotate: false, shotOffset: 0, range: 150 },
        resource: 20,
        life: 65,
    },

    {
        name: 'upgrade_2',
        image: { src: 'assets/item_tower2_2.png', regX: 32, regY: 90 },
        icon: { src: 'assets/icon_tower2_2.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
        ammo: { src: 'assets/item_ammo2.png', regX: 0, regY: 50, speed: 50, get life() { return 0.9 * ammoFire; }, time: 0.1, freeze: 0, rotate: false, shotOffset: 0, range: 150 },
        resource: 30,
        life: 70,
    },
    {
        name: 'upgrade_3',
        image: { src: 'assets/item_tower2_3.png', regX: 32, regY: 90 },
        icon: { src: 'assets/icon_tower2_3.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
        ammo: { src: 'assets/item_ammo2_3.png', regX: 0, regY: 50, speed: 50, get life() { return 1.2 * ammoFire; }, time: 0.1, freeze: 0, rotate: false, shotOffset: 0, range: 150 },
        resource: 50,
        life: 80,
    }]
},
{
    name: 'cloud',
    sound: 'assets/sounds/ammo_arrow.ogg',
    image: { src: 'assets/item_tower1.png', regX: 32, regY: 90 },
    icon: { src: 'assets/icon_tower1.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
    ammo: { src: 'assets/item_ammo1.png', regX: 0, regY: 50, speed: 8, get life() { return 4 * ammoFire; }, time: 1, freeze: 0, rotate: false, shotOffset: 0, range: 280 },
    resource: 50,
    hitOffset: -30,
    life: 70,
    bar: { width: 40, height: 5, offset: -95 },
    upgrade: [{
        name: 'upgrade_1',
        image: { src: 'assets/item_tower1_1.png', regX: 32, regY: 90 },
        icon: { src: 'assets/icon_tower1_1.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
        ammo: { src: 'assets/item_ammo1.png', regX: 0, regY: 50, speed: 8, get life() { return 6 * ammoFire; }, time: 1, freeze: 0, rotate: false, shotOffset: 0, range: 280 },
        resource: 40,
        life: 75,
    },

    {
        name: 'upgrade_2',
        image: { src: 'assets/item_tower1_2.png', regX: 32, regY: 90 },
        icon: { src: 'assets/icon_tower1_2.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
        ammo: { src: 'assets/item_ammo1.png', regX: 0, regY: 50, speed: 8, get life() { return 8 * ammoFire; }, time: 1, freeze: 0, rotate: false, shotOffset: 0, range: 280 },
        resource: 60,
        life: 80,
    },
    {
        name: 'upgrade_3',
        image: { src: 'assets/item_tower1_3.png', regX: 32, regY: 90 },
        icon: { src: 'assets/icon_tower1_3.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
        ammo: { src: 'assets/item_ammo1_3.png', regX: 0, regY: 50, speed: 8, get life() { return 10 * ammoFire; }, time: 1, freeze: 0, rotate: false, shotOffset: 0, range: 280 },
        resource: 80,
        life: 90,
    }]
},
{
    name: 'snowball',
    sound: 'assets/sounds/ammo_ice.ogg',
    image: { src: 'assets/item_tower3.png', regX: 29, regY: 90 },
    icon: { src: 'assets/icon_tower3.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
    ammo: { src: 'assets/item_ammo3.png', regX: 0, regY: 0, speed: 4, get life() { return 5 * ammoFire; }, time: 1, freeze: 1, rotate: false, shotOffset: 0, range: 200 },
    resource: 50,
    hitOffset: -30,
    life: 50,
    bar: { width: 40, height: 5, offset: -100 }
},
{
    name: 'fish',
    sound: 'assets/sounds/ammo_cannon.ogg',
    image: { src: 'assets/item_tower4.png', regX: 32, regY: 54 },
    icon: { src: 'assets/icon_tower4.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
    ammo: { src: 'assets/item_ammo4.png', regX: 0, regY: 50, speed: 8, get life() { return 9 * ammoFire; }, time: 1, freeze: 0, rotate: false, shotOffset: 0, range: 200 },
    resource: 70,
    hitOffset: -30,
    life: 90,
    bar: { width: 40, height: 5, offset: -65 }
},
{
    name: 'fire',
    sound: 'assets/sounds/ammo_cannon.ogg',
    image: { src: 'assets/item_tower5.png', regX: 32, regY: 61 },
    icon: { src: 'assets/icon_tower5.png', disable: 'assets/icon_tower_disable.png', regX: 26, regY: 27 },
    ammo: { src: 'assets/item_ammo5.png', regX: 0, regY: 50, speed: 8, get life() { return 13 * ammoFire; }, time: 1, freeze: 0, rotate: false, shotOffset: 0, range: 400 },
    resource: 120,
    hitOffset: -30,
    life: 100,
    bar: { width: 40, height: 5, offset: -65 }
}];